-- ============================================================
-- 17_exercises_seed_100.sql
-- AI 운동 루틴 추천의 1차 후보 카탈로그 (총 100개).
--
-- 큐레이션 기준:
--   - 너무 비슷한 것 제외, 유명한 종류 위주
--   - 부위 4 × 20 + 스트레칭 20 = 100, 균등 분포
--   - 스트레칭은 phase_tags 로 세분: warmup / cooldown / recovery
--
-- 멘트 차별화:
--   - 세트 기반: middle_reps(공통 풀) + form_cues(운동 특화 2~3개)
--     런타임에 middle_reps 슬롯 0/2/4 자리에 form_cues 가 끼어듦.
--   - 시간 기반: time_scripts 를 운동별로 specific 하게 inline.
-- ============================================================

do $$
declare
  -- ── 세트 기반 generic 풀 ────────────────────────────────────
  -- form_cues 가 슬롯 0/2/4 에 끼어들고, 1/3 만 generic 으로 남는 구조.
  -- 슬롯 0/2/4 의 generic 값은 form_cues 가 없을 때 fallback.
  m_general text[] := array[
    '{count}, 호흡을 유지하세요.',
    '{count}, 좋아요. 자세 신경쓰면서 갑니다.',
    '{count}, 천천히 컨트롤해요.',
    '{count}, 코어에 힘을 주세요.',
    '{count}, 자세 좋아요.'
  ];
  m_cardio text[] := array[
    '{count}, 호흡을 같이 가요.',
    '{count}, 리듬을 유지해요.',
    '{count}, 시선은 앞을 봐요.',
    '{count}, 코어를 단단히 하세요.',
    '{count}, 자세 좋아요.'
  ];
  m_dumbbell text[] := array[
    '{count}, 호흡을 유지하세요.',
    '{count}, 덤벨은 흔들리지 않게 합니다.',
    '{count}, 천천히 컨트롤해요.',
    '{count}, 어깨를 내리세요.',
    '{count}, 자세를 정확히 유지하세요.'
  ];
  m_easy text[] := array[
    '{count}, 편안하게 호흡하세요.',
    '{count}, 호흡을 같이 가주세요.',
    '{count}, 천천히 자세를 신경써주세요.',
    '{count}, 어깨 힘을 빼세요.',
    '{count}, 좋아요.'
  ];

  e_general text[] := array['{count}, 자세 잡고 천천히 시작해요.', '{count}, 좋아요. 호흡 같이 가요.'];
  e_easy text[] := array['{count}, 가볍게 시작해요. 호흡은 편하게.', '{count}, 좋아요. 무리하지 말고요.'];
  e_focus text[] := array['{count}, 자세 정확히 잡아요.', '{count}, 좋아요. 코어에 힘을 줍니다.'];

  f_general text[] := array['{count}, 거의 다 왔어요.', '{count}, 한 번만 더 가요.', '{count}, 마지막이에요. 천천히 마무리해요.'];
  f_strong text[] := array['{count}, 마지막 세 번. 힘내요.', '{count}, 두 번 남았어요.', '{count}, 마지막이에요. 끝까지 마무리합니다.'];
  f_gentle text[] := array['{count}, 거의 끝났어요.', '{count}, 한 번만 더요.', '{count}, 마지막. 천천히 마무리해요.'];

begin

insert into public.exercises (
  name, body_region, exercise_type, goal_tags, place_tags, phase_tags,
  target_parts, contraindicated_parts, equipment, is_high_impact, intensity,
  default_sets, default_reps, min_reps, max_reps,
  default_duration_sec, min_duration_sec, max_duration_sec,
  description_text, caution_text,
  early_reps, middle_reps, final_reps, time_scripts, halfway_encouragement,
  form_cues
) values

-- ============================================================
-- 상체 (1-20) : 가슴·어깨·등·팔
-- ============================================================
('푸시업', '상체', array['근력'], array['체력 향상','자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['가슴','어깨','삼두'], array['손목','어깨'], array[]::text[],
 false, 3, 3, 10, 6, 18, null, null, null,
 '손을 어깨 너비로 짚고 몸을 일직선으로 유지한 채 내려갔다 올라옵니다.',
 '허리가 처지지 않게 코어에 힘 주세요.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 가슴이 바닥에 닿을 듯 내려가요.','{count}, 팔꿈치는 옆구리쪽 45도로요.','{count}, 어깨가 귀에 붙지 않게 합니다.']),

('무릎 푸시업', '상체', array['근력'], array['체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['가슴','어깨','삼두'], array['손목'], array['매트'],
 false, 2, 3, 12, 8, 20, null, null, null,
 '무릎을 바닥에 댄 채 푸시업 자세로 천천히 내려갔다 올라옵니다.',
 '손목이 아프면 주먹을 쥐고 해도 좋아요.',
 e_easy, m_general, f_gentle, array[]::text[], '',
 array['{count}, 무릎부터 머리까지 일직선으로 유지합니다.','{count}, 가슴부터 천천히 바닥으로 내려갑니다.','{count}, 손목 바로 위에 어깨 두세요.']),

('인클라인 푸시업', '상체', array['근력'], array['체력 향상'],
 array['집','야외','헬스장'], array['warmup','main'],
 array['가슴','어깨'], array['손목'], array[]::text[],
 false, 2, 3, 12, 8, 20, null, null, null,
 '의자나 벤치에 손을 짚고 몸을 비스듬히 한 채 푸시업해요.',
 '팔꿈치가 너무 벌어지지 않게 45도 정도로요.',
 e_easy, m_general, f_gentle, array[]::text[], '',
 array['{count}, 의자를 단단히 짚어요.','{count}, 가슴부터 의자에 가까이 내려옵니다.','{count}, 몸은 비스듬한 일직선이요.']),

('다이아몬드 푸시업', '상체', array['근력'], array['체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['삼두','가슴'], array['손목','어깨'], array[]::text[],
 false, 4, 3, 8, 4, 12, null, null, null,
 '엄지와 검지로 다이아몬드를 만들어 손을 모은 뒤 푸시업해요.',
 '난이도 높습니다. 힘들다면 무릎 푸시업으로 대체해보세요.',
 e_focus, m_general, f_strong, array[]::text[], '',
 array['{count}, 손가락은 다이아몬드 모양 유지합니다.','{count}, 팔꿈치는 옆구리에 붙여요.','{count}, 삼두로 미는 느낌이에요.']),

('파이크 푸시업', '상체', array['근력'], array['체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['어깨','삼두'], array['어깨','손목'], array['매트'],
 false, 4, 3, 8, 4, 12, null, null, null,
 '엉덩이를 높게 들고 머리가 바닥에 닿도록 내려갔다 올라옵니다.',
 '어깨에 통증 있으면 즉시 중단하세요.',
 e_focus, m_general, f_strong, array[]::text[], '',
 array['{count}, 엉덩이를 최대한 천장으로.','{count}, 머리가 손 사이로 내려가요.','{count}, 어깨로 밀어 올려요.']),

('트라이셉 딥', '상체', array['근력'], array['체력 향상'],
 array['집','헬스장'], array['main'],
 array['삼두','어깨'], array['어깨','손목'], array[]::text[],
 false, 3, 3, 10, 6, 15, null, null, null,
 '의자 끝을 짚고 엉덩이를 들어 팔꿈치를 굽혔다 폅니다.',
 '어깨가 너무 떨어지지 않게 주의하세요.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 엉덩이를 의자 가까이로요.','{count}, 팔꿈치는 뒤로 곧게요.','{count}, 어깨가 솟지 않게요.']),

('슈퍼맨', '상체', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['등','엉덩이'], array[]::text[], array['매트'],
 false, 2, 3, 12, 8, 20, null, null, null,
 '엎드린 자세에서 팔과 다리를 동시에 들어올려 등을 조여요.',
 '허리에 통증 있으면 팔만 들어요.',
 e_easy, m_general, f_gentle, array[]::text[], '',
 array['{count}, 팔과 다리를 동시에 들어올립니다.','{count}, 엉덩이를 꽉 조여요.','{count}, 목은 자연스럽게 유지하세요.']),

('인버티드 로우', '상체', array['근력'], array['자세 개선','체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['등','이두'], array['어깨'], array[]::text[],
 false, 3, 3, 10, 6, 15, null, null, null,
 '봉이나 단단한 테이블 아래 누워 가슴을 봉 쪽으로 당겨요.',
 '단단한 지지대가 필수에요. 흔들리면 위험합니다.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 가슴을 봉 쪽으로 당겨요.','{count}, 견갑골을 조여요.','{count}, 몸은 일직선 유지합니다.']),

('풀업', '상체', array['근력'], array['체력 향상'],
 array['헬스장'], array['main'],
 array['등','이두','어깨'], array['어깨'], array[]::text[],
 false, 4, 3, 8, 3, 12, null, null, null,
 '봉에 매달려 턱이 봉 위로 올라가도록 몸을 당겨 올려요.',
 '어려우면 밴드 보조나 점프 풀업으로.',
 e_focus, m_general, f_strong, array[]::text[], '',
 array['{count}, 턱을 봉 위로 올려요.','{count}, 견갑골을 먼저 내려요.','{count}, 천천히 컨트롤하며 내려요.']),

('덤벨 숄더 프레스', '상체', array['근력'], array['체력 향상','자세 개선'],
 array['집','헬스장'], array['main'],
 array['어깨','삼두'], array['어깨','허리'], array['덤벨'],
 false, 3, 3, 10, 6, 15, null, null, null,
 '덤벨을 어깨 위에서 머리 위로 밀어 올렸다 천천히 내립니다.',
 '허리가 꺾이지 않게 코어에 힘을 주세요.',
 e_general, m_dumbbell, f_general, array[]::text[], '',
 array['{count}, 덤벨을 머리 위로 곧게 밀어요.','{count}, 팔꿈치는 약간 앞으로.','{count}, 천천히 어깨 옆으로 내려요.']),

('덤벨 바이셉 컬', '상체', array['근력'], array['체력 향상'],
 array['집','헬스장'], array['main'],
 array['이두'], array[]::text[], array['덤벨'],
 false, 3, 3, 12, 8, 18, null, null, null,
 '덤벨을 들고 팔꿈치를 고정한 채 어깨 쪽으로 들어올렸다 내려요.',
 '반동 쓰지 말고 천천히 올렸다 내립니다.',
 e_general, m_dumbbell, f_general, array[]::text[], '',
 array['{count}, 팔꿈치를 옆구리에 고정하세요.','{count}, 덤벨을 어깨까지 천천히 올리고 천천히 내립니다.','{count}, 내릴 때 더 천천히요.']),

('덤벨 해머 컬', '상체', array['근력'], array['체력 향상'],
 array['집','헬스장'], array['main'],
 array['이두','전완'], array[]::text[], array['덤벨'],
 false, 3, 3, 12, 8, 18, null, null, null,
 '덤벨을 망치 잡듯 세로로 잡고 손바닥이 마주보게 컬해요.',
 '반동 쓰지 마세요.',
 e_general, m_dumbbell, f_general, array[]::text[], '',
 array['{count}, 손바닥이 서로 마주보게요.','{count}, 팔꿈치 옆구리 고정.','{count}, 컨트롤하며 내려요.']),

('덤벨 트라이셉 익스텐션', '상체', array['근력'], array['체력 향상'],
 array['집','헬스장'], array['main'],
 array['삼두'], array['어깨'], array['덤벨'],
 false, 3, 3, 10, 6, 15, null, null, null,
 '덤벨 하나를 양손으로 머리 뒤로 내렸다 펴 올려요.',
 '팔꿈치를 좁게 고정한 채로요.',
 e_general, m_dumbbell, f_general, array[]::text[], '',
 array['{count}, 팔꿈치는 머리 옆에 고정.','{count}, 머리 뒤로 천천히 내려요.','{count}, 팔꿈치 안 벌어지게 내렸다 올립니다.']),

('덤벨 로우', '상체', array['근력'], array['자세 개선','체력 향상'],
 array['집','헬스장'], array['main'],
 array['등','이두'], array['허리'], array['덤벨'],
 false, 3, 3, 10, 6, 15, null, null, null,
 '한 손은 의자에 짚고 다른 손의 덤벨을 옆구리로 당겨요.',
 '등을 평평하게, 허리를 꺾지 마세요.',
 e_general, m_dumbbell, f_general, array[]::text[], '',
 array['{count}, 등으로 당기는 느낌으로요.','{count}, 팔꿈치를 옆구리 쪽으로요.','{count}, 허리는 평평하게요.']),

('덤벨 플라이', '상체', array['근력'], array['체력 향상'],
 array['집','헬스장'], array['main'],
 array['가슴','어깨'], array['어깨'], array['덤벨','매트'],
 false, 3, 3, 12, 8, 18, null, null, null,
 '누운 자세에서 덤벨을 양옆으로 펼쳤다 모아요.',
 '팔꿈치는 살짝 굽힌 채 유지.',
 e_general, m_dumbbell, f_general, array[]::text[], '',
 array['{count}, 팔꿈치는 살짝 굽힌 채로요.','{count}, 가슴 위로 모아요.','{count}, 천천히 양옆으로 펼쳐요.']),

('덤벨 사이드 레이즈', '상체', array['근력'], array['체력 향상'],
 array['집','헬스장'], array['main'],
 array['어깨'], array['어깨'], array['덤벨'],
 false, 3, 3, 12, 8, 18, null, null, null,
 '덤벨을 양옆으로 어깨 높이까지 들어올렸다 내려요.',
 '반동 쓰지 말고 천천히, 어깨 으쓱 금지.',
 e_general, m_dumbbell, f_general, array[]::text[], '',
 array['{count}, 어깨 높이까지 들어요.','{count}, 손등이 천장 향하게요.','{count}, 어깨 으쓱하지 마세요.']),

('덤벨 프론트 레이즈', '상체', array['근력'], array['체력 향상'],
 array['집','헬스장'], array['warmup','main'],
 array['어깨'], array['어깨'], array['덤벨'],
 false, 2, 3, 12, 8, 18, null, null, null,
 '덤벨을 정면으로 어깨 높이까지 들어올렸다 내려요.',
 '허리 꺾지 말고 코어로 버텨요.',
 e_easy, m_dumbbell, f_gentle, array[]::text[], '',
 array['{count}, 앞으로 어깨 높이까지요.','{count}, 팔꿈치 살짝만 굽혀요.','{count}, 반동 없이 천천히요.']),

('덤벨 풀오버', '상체', array['근력'], array['체력 향상'],
 array['집','헬스장'], array['main'],
 array['가슴','등'], array['어깨'], array['덤벨','매트'],
 false, 3, 3, 12, 8, 18, null, null, null,
 '누워 덤벨 하나를 양손으로 잡고 머리 뒤로 내렸다 가슴 위로 올려요.',
 '허리 뜨지 않게 코어로 눌러요.',
 e_general, m_dumbbell, f_general, array[]::text[], '',
 array['{count}, 덤벨을 머리 뒤로 내려요.','{count}, 가슴 늘어나는 느낌까지요.','{count}, 가슴 위로 다시 올려요.']),

('덤벨 리버스 플라이', '상체', array['근력'], array['자세 개선'],
 array['집','헬스장'], array['main'],
 array['후면 어깨','등'], array['허리'], array['덤벨'],
 false, 3, 3, 12, 8, 18, null, null, null,
 '상체를 숙인 채 덤벨을 양옆으로 날개처럼 펼쳤다 모아요.',
 '등을 평평하게, 허리 둥글지 않게.',
 e_general, m_dumbbell, f_general, array[]::text[], '',
 array['{count}, 양옆으로 날개처럼 펼쳐요.','{count}, 견갑골을 조여요.','{count}, 등을 평평하게 유지요.']),

('덤벨 슈러그', '상체', array['근력'], array['자세 개선'],
 array['집','헬스장'], array['main'],
 array['승모근'], array[]::text[], array['덤벨'],
 false, 2, 3, 15, 10, 20, null, null, null,
 '덤벨을 양옆으로 든 채 어깨를 귀 쪽으로 들어 올렸다 내려요.',
 '목을 앞으로 빼지 마세요.',
 e_easy, m_dumbbell, f_gentle, array[]::text[], '',
 array['{count}, 어깨를 귀 쪽으로 들어요.','{count}, 정점에서 1초 유지.','{count}, 천천히 내려요.']),

-- ============================================================
-- 하체 (21-40) : 엉덩이·허벅지·종아리
-- ============================================================
('스쿼트', '하체', array['근력'], array['체력 향상','자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['허벅지 앞','엉덩이','코어'], array['무릎'], array[]::text[],
 false, 3, 3, 12, 8, 20, null, null, null,
 '발을 어깨 너비로 벌리고 의자에 앉듯 엉덩이를 뒤로 빼며 내려가요.',
 '무릎이 발끝 안쪽으로 모이지 않게 주의.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 엉덩이를 의자에 앉듯 뒤로요.','{count}, 무릎이 발끝 방향과 같게.','{count}, 가슴 들고 시선 앞으로.']),

('점프 스쿼트', '하체', array['복합','유산소'], array['체중 감량','체력 향상'],
 array['야외','헬스장'], array['main'],
 array['허벅지 앞','엉덩이','종아리'], array['무릎','허리'], array[]::text[],
 true, 4, 3, 10, 5, 15, null, null, null,
 '스쿼트로 내려갔다 폭발적으로 점프해 올라와요.',
 '무릎으로 착지하지 말고 발 전체로 부드럽게.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 내려가서 폭발적으로 점프!','{count}, 발 전체로 부드럽게 착지요.','{count}, 바로 다음 스쿼트로 이어요.']),

('스모 스쿼트', '하체', array['근력'], array['체력 향상','자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['허벅지 안쪽','엉덩이'], array['무릎'], array[]::text[],
 false, 3, 3, 12, 8, 20, null, null, null,
 '발을 매우 넓게 벌리고 발끝을 45도 바깥으로 향한 채 스쿼트해요.',
 '무릎이 안쪽으로 모이지 않게.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 발끝을 45도 바깥으로요.','{count}, 무릎을 발끝 방향으로요.','{count}, 엉덩이는 아래로 곧게요.']),

('불가리안 스플릿 스쿼트', '하체', array['근력'], array['체력 향상'],
 array['집','헬스장'], array['main'],
 array['허벅지 앞','엉덩이'], array['무릎'], array[]::text[],
 false, 4, 3, 8, 5, 12, null, null, null,
 '한 발을 의자에 올리고 앞 다리만으로 스쿼트해요.',
 '앞 무릎이 발끝을 넘지 않게.',
 e_focus, m_general, f_strong, array[]::text[], '',
 array['{count}, 앞 다리에 체중을 실어요.','{count}, 뒤 다리는 의자에 살짝만.','{count}, 앞 무릎 발끝 안 넘게요.']),

('월 시트', '하체', array['근력'], array['체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['허벅지 앞','엉덩이'], array['무릎'], array[]::text[],
 false, 3, null, null, null, null, 45, 20, 90,
 '벽에 등을 대고 의자에 앉은 듯한 자세로 무릎 90도를 유지해요.',
 '무릎 통증 시 즉시 중단.',
 array[]::text[], array[]::text[], array[]::text[],
 array['벽에 등을 평평히 붙여요.','무릎이 90도가 되게 내려요.','허벅지가 바닥과 평행해요.','복근에 힘 단단히 주세요.','호흡 유지하세요.'],
 '절반 지났어요. 잘 버티고 있어요.',
 array[]::text[]),

('포워드 런지', '하체', array['근력'], array['체력 향상','자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['허벅지 앞','엉덩이'], array['무릎'], array[]::text[],
 false, 3, 3, 10, 6, 16, null, null, null,
 '한 발을 앞으로 크게 내디뎌 무릎을 90도로 굽혔다 돌아와요.',
 '앞 무릎이 발끝을 넘지 않게요.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 앞으로 크게 한 걸음 내디뎌요.','{count}, 앞 무릎이 90도 되도록요.','{count}, 상체는 꼿꼿이 유지해요.']),

('백 런지', '하체', array['근력'], array['체력 향상','자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['허벅지 앞','엉덩이'], array['무릎'], array[]::text[],
 false, 3, 3, 10, 6, 16, null, null, null,
 '한 발을 뒤로 크게 보내 무릎을 굽혔다 돌아와요.',
 '상체는 꼿꼿이, 코어 잡아요.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 뒤로 한 걸음 보내요.','{count}, 앞 무릎을 90도 굽혀요.','{count}, 앞 무릎이 발끝 안 넘게요.']),

('사이드 런지', '하체', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['허벅지 안쪽','엉덩이'], array['무릎'], array[]::text[],
 false, 3, 3, 10, 6, 16, null, null, null,
 '한쪽으로 크게 발을 벌려 그쪽 무릎을 굽히며 내려가요.',
 '굽힌 쪽 무릎이 발끝 방향과 같게.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 한쪽으로 크게 벌리며 내려가요.','{count}, 굽힌 무릎이 발끝과 같게.','{count}, 반대 다리는 곧게 펴요.']),

('커시 런지', '하체', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['엉덩이','허벅지 옆'], array['무릎'], array[]::text[],
 false, 3, 3, 10, 6, 14, null, null, null,
 '한 발을 반대편 사선 뒤로 보내 인사하듯 무릎을 굽혀요.',
 '균형이 어려우면 의자 잡아도 좋아요.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 뒤 사선으로 인사하듯 내려요.','{count}, 앞 무릎은 정면 유지요.','{count}, 엉덩이 옆 자극 느껴봐요.']),

('점프 런지', '하체', array['복합','유산소'], array['체중 감량','체력 향상'],
 array['야외','헬스장'], array['main'],
 array['허벅지 앞','엉덩이'], array['무릎','허리'], array[]::text[],
 true, 4, 3, 10, 5, 14, null, null, null,
 '런지 자세에서 점프해 다리를 바꿔 착지해요.',
 '무릎 부담 큼. 통증 시 즉시 중단.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 점프해서 다리를 교차해요.','{count}, 부드럽게 착지하세요.','{count}, 코어 단단히 잡아요.']),

('글루트 브릿지', '하체', array['근력'], array['자세 개선','체력 향상'],
 array['집','야외','헬스장'], array['main','warmup'],
 array['엉덩이','허벅지 뒤'], array[]::text[], array['매트'],
 false, 2, 3, 12, 8, 20, null, null, null,
 '누운 자세에서 무릎을 굽히고 엉덩이를 천천히 들어올렸다 내려요.',
 '허리를 과하게 꺾지 말고 엉덩이에 힘.',
 e_easy, m_general, f_gentle, array[]::text[], '',
 array['{count}, 엉덩이를 천장 쪽으로 들어요.','{count}, 정점에서 엉덩이 꽉 조여요.','{count}, 천천히 내려와요.']),

('싱글 레그 글루트 브릿지', '하체', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['엉덩이','허벅지 뒤'], array[]::text[], array['매트'],
 false, 3, 3, 10, 6, 15, null, null, null,
 '한 발을 들어올린 채로 글루트 브릿지해요.',
 '엉덩이가 한쪽으로 기울지 않게.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 한 발 든 채 엉덩이 올려요.','{count}, 정점에서 1초 유지.','{count}, 골반이 기울지 않게요.']),

('힙 쓰러스트', '하체', array['근력'], array['자세 개선'],
 array['집','헬스장'], array['main'],
 array['엉덩이','허벅지 뒤'], array[]::text[], array['매트'],
 false, 3, 3, 12, 8, 18, null, null, null,
 '의자에 어깨를 기대고 엉덩이를 들어 무릎까지 일직선으로요.',
 '허리가 꺾이지 않게 갈비뼈 닫아요.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 엉덩이를 무릎 높이까지요.','{count}, 갈비뼈를 닫는 느낌으로요.','{count}, 정점에서 엉덩이 조여요.']),

('도노키 킥', '하체', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['엉덩이'], array[]::text[], array['매트'],
 false, 2, 3, 12, 8, 18, null, null, null,
 '네발 자세에서 한 다리의 무릎을 굽힌 채 발바닥으로 천장을 차요.',
 '골반이 흔들리지 않게.',
 e_easy, m_general, f_gentle, array[]::text[], '',
 array['{count}, 무릎 굽힌 채 발바닥으로 천장 차요.','{count}, 골반이 흔들리지 않게요.','{count}, 엉덩이 위쪽 자극 느껴요.']),

('파이어 하이드런트', '하체', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['warmup','main'],
 array['엉덩이 옆','고관절'], array[]::text[], array['매트'],
 false, 2, 3, 12, 8, 18, null, null, null,
 '네발 자세에서 한 다리를 옆으로 90도 들어 올렸다 내려요.',
 '골반이 옆으로 기울지 않게.',
 e_easy, m_general, f_gentle, array[]::text[], '',
 array['{count}, 옆으로 무릎을 들어 올려요.','{count}, 골반은 정면 유지요.','{count}, 엉덩이 옆 자극 느껴요.']),

('클램쉘', '하체', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['warmup','main'],
 array['엉덩이 옆','고관절'], array[]::text[], array['매트'],
 false, 2, 3, 15, 10, 25, null, null, null,
 '옆으로 누워 무릎을 굽힌 채 위쪽 무릎만 천천히 들었다 내려요.',
 '엉덩이가 뒤로 빠지지 않게.',
 e_easy, m_general, f_gentle, array[]::text[], '',
 array['{count}, 위쪽 무릎만 천장 쪽으로요.','{count}, 골반이 뒤로 빠지지 않게요.','{count}, 엉덩이 옆 자극 느껴요.']),

('카프 레이즈', '하체', array['근력'], array['체력 향상'],
 array['집','야외','헬스장'], array['warmup','main'],
 array['종아리'], array[]::text[], array[]::text[],
 false, 2, 3, 15, 10, 25, null, null, null,
 '발끝으로 천천히 올라섰다 내려와요.',
 '균형 어려우면 벽을 짚어요.',
 e_easy, m_general, f_gentle, array[]::text[], '',
 array['{count}, 발끝으로 최대한 높이 올라가요.','{count}, 정점에서 1초 멈춰요.','{count}, 천천히 발뒤꿈치 내려요.']),

('덤벨 루마니안 데드리프트', '하체', array['근력'], array['자세 개선','체력 향상'],
 array['집','헬스장'], array['main'],
 array['햄스트링','엉덩이','허리'], array['허리'], array['덤벨'],
 false, 4, 3, 8, 5, 12, null, null, null,
 '덤벨을 든 채 엉덩이를 뒤로 빼며 상체를 숙였다 일어나요.',
 '허리는 굽히지 말고 엉덩이로 접어요.',
 e_focus, m_dumbbell, f_strong, array[]::text[], '',
 array['{count}, 엉덩이를 뒤로 빼며 숙여요.','{count}, 등은 평평하게 유지요.','{count}, 햄스트링 늘어나는 느낌까지요.']),

('덤벨 스쿼트', '하체', array['근력'], array['체력 향상'],
 array['집','헬스장'], array['main'],
 array['허벅지 앞','엉덩이','코어'], array['무릎'], array['덤벨'],
 false, 4, 3, 10, 6, 14, null, null, null,
 '덤벨을 어깨 또는 옆에 들고 스쿼트해요.',
 '무릎이 발끝 방향과 같게.',
 e_general, m_dumbbell, f_strong, array[]::text[], '',
 array['{count}, 덤벨 어깨에 안정적으로요.','{count}, 엉덩이부터 뒤로 빼며 앉아요.','{count}, 가슴 들고 천천히요.']),

('덤벨 런지', '하체', array['근력'], array['체력 향상'],
 array['집','헬스장'], array['main'],
 array['허벅지 앞','엉덩이'], array['무릎'], array['덤벨'],
 false, 4, 3, 10, 6, 14, null, null, null,
 '덤벨을 양손에 들고 런지해요.',
 '상체 꼿꼿이, 코어 단단히.',
 e_general, m_dumbbell, f_strong, array[]::text[], '',
 array['{count}, 덤벨 들고 균형 잡으며 내려요.','{count}, 앞 무릎 90도까지요.','{count}, 상체 꼿꼿이 유지요.']),

-- ============================================================
-- 코어 (41-60) : 복근·허리·옆구리
-- ============================================================
('플랭크', '코어', array['근력'], array['자세 개선','체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['코어','어깨'], array['허리','어깨'], array['매트'],
 false, 3, null, null, null, null, 45, 20, 90,
 '팔꿈치와 발끝으로 몸을 지지하며 일직선으로 버텨요.',
 '엉덩이가 처지거나 솟지 않게.',
 array[]::text[], array[]::text[], array[]::text[],
 array['어깨를 손목 바로 위에 두세요.','엉덩이가 처지지 않게 골반 들어요.','시선은 바닥 한 점을 봐요.','복근에 힘 단단히 주세요.','호흡 깊게 들이마시고 내쉬어요.'],
 '절반 지났어요. 호흡 유지하세요.',
 array[]::text[]),

('사이드 플랭크', '코어', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['옆구리','어깨'], array['어깨','허리'], array['매트'],
 false, 2, null, null, null, null, 30, 15, 60,
 '한쪽 팔꿈치로 지지하며 옆으로 몸을 일직선으로 들어요.',
 '어깨에 통증 있으면 무릎을 바닥에.',
 array[]::text[], array[]::text[], array[]::text[],
 array['팔꿈치는 어깨 바로 아래.','엉덩이가 떨어지지 않게.','옆구리에 힘 단단히.','호흡 유지하세요.'],
 '절반 지났어요. 잘 버티고 있어요.',
 array[]::text[]),

('리버스 플랭크', '코어', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['코어','등','엉덩이'], array['손목','어깨'], array['매트'],
 false, 2, null, null, null, null, 30, 15, 60,
 '앉은 자세에서 손으로 바닥을 짚고 엉덩이를 들어 몸을 일직선으로요.',
 '손목 부담 크면 짧게.',
 array[]::text[], array[]::text[], array[]::text[],
 array['손은 어깨 아래에.','엉덩이 끝까지 들어 올려요.','시선은 천장으로요.','몸은 일직선 유지요.'],
 '절반 지났어요. 조금만 더요.',
 array[]::text[]),

('할로우 홀드', '코어', array['근력'], array['체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['코어'], array['허리'], array['매트'],
 false, 3, null, null, null, null, 30, 15, 60,
 '누워 어깨와 다리를 살짝 들어 몸을 바나나 모양으로 유지해요.',
 '허리 통증 시 즉시 중단.',
 array[]::text[], array[]::text[], array[]::text[],
 array['턱을 가슴 쪽으로 살짝 당겨요.','다리는 모아 살짝 들어요.','허리는 바닥에 눌러요.','복근에 힘 단단히 주세요.','호흡 유지하세요.'],
 '절반 지났어요. 잘 버티고 있어요.',
 array[]::text[]),

('크런치', '코어', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['상복부'], array['허리','목'], array['매트'],
 false, 2, 3, 15, 10, 25, null, null, null,
 '누워 무릎을 굽힌 채 상체만 살짝 말아 올렸다 내려요.',
 '목을 잡아당기지 말고 복근 힘으로.',
 e_easy, m_general, f_gentle, array[]::text[], '',
 array['{count}, 상체만 살짝 말아 올려요.','{count}, 복근 힘으로 들어요.','{count}, 목 잡아당기지 마세요.']),

('시트업', '코어', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['상복부','하복부'], array['허리','목'], array['매트'],
 false, 3, 3, 12, 8, 18, null, null, null,
 '누운 자세에서 상체를 완전히 일으켜 앉았다 천천히 내려요.',
 '목 잡아당기지 마세요.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 손은 가슴 위 또는 머리 옆에요.','{count}, 끝까지 일어났다 내려요.','{count}, 천천히 컨트롤해요.']),

('리버스 크런치', '코어', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['하복부'], array['허리'], array['매트'],
 false, 3, 3, 12, 8, 18, null, null, null,
 '누워 무릎을 가슴 쪽으로 말아 올려 엉덩이를 띄웠다 내려요.',
 '반동 쓰지 말고 천천히.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 무릎을 가슴 쪽으로 말아요.','{count}, 엉덩이를 띄웠다 내려요.','{count}, 반동 쓰지 마세요.']),

('바이시클 크런치', '코어', array['근력','유산소'], array['체중 감량','자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['코어','옆구리'], array['목','허리'], array['매트'],
 false, 3, 3, 16, 10, 24, null, null, null,
 '누워 자전거 페달 밟듯 반대편 무릎과 팔꿈치를 마주쳐요.',
 '목 잡아당기지 말고 코어로요.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 반대 팔꿈치와 무릎 마주쳐요.','{count}, 자전거 페달처럼 교차요.','{count}, 목 잡아당기지 마세요.']),

('레그 레이즈', '코어', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['하복부'], array['허리'], array['매트'],
 false, 3, 3, 10, 6, 16, null, null, null,
 '누운 자세에서 다리를 모아 천천히 올렸다 바닥에 안 닿게 내려요.',
 '허리가 뜨면 손을 엉덩이 밑에.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 다리 모아 천천히 올려요.','{count}, 바닥에 안 닿게 내려요.','{count}, 허리 뜨면 손 엉덩이 밑에요.']),

('행잉 레그 레이즈', '코어', array['근력'], array['체력 향상'],
 array['헬스장'], array['main'],
 array['하복부','코어'], array['어깨','허리'], array[]::text[],
 false, 4, 3, 10, 5, 14, null, null, null,
 '봉에 매달려 다리를 모은 채 90도까지 올렸다 내려요.',
 '반동 쓰지 말고 코어로 컨트롤.',
 e_focus, m_general, f_strong, array[]::text[], '',
 array['{count}, 봉에 매달려 다리 들어요.','{count}, 반동 쓰지 마세요.','{count}, 코어 힘으로 들어요.']),

('플러터 킥', '코어', array['근력','유산소'], array['체중 감량'],
 array['집','야외','헬스장'], array['main'],
 array['하복부','허벅지 앞'], array['허리'], array['매트'],
 false, 3, 3, 20, 12, 30, null, null, null,
 '누운 자세에서 다리를 살짝 들고 위아래로 빠르게 교차해요.',
 '허리가 뜨지 않게 코어로 눌러요.',
 e_general, m_general, f_strong, array[]::text[], '',
 array['{count}, 다리 살짝 들고 위아래 교차요.','{count}, 허리는 바닥 눌러요.','{count}, 호흡 유지하세요.']),

('시저 킥', '코어', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['하복부','허벅지 안쪽'], array['허리'], array['매트'],
 false, 3, 3, 16, 10, 24, null, null, null,
 '누운 자세에서 다리를 좌우로 가위질하듯 교차해요.',
 '허리가 뜨지 않게.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 다리 좌우 가위질로 교차요.','{count}, 허리 뜨지 않게요.','{count}, 다리는 곧게 펴요.']),

('러시안 트위스트', '코어', array['근력'], array['체중 감량','자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['옆구리','코어'], array['허리'], array['매트'],
 false, 3, 3, 16, 10, 24, null, null, null,
 '앉은 자세로 다리를 띄우고 상체를 좌우로 천천히 회전해요.',
 '허리가 둥글게 말리지 않게.',
 e_general, m_general, f_general, array[]::text[], '',
 array['{count}, 상체 좌우로 천천히 회전.','{count}, 다리는 띄운 채 유지요.','{count}, 허리 둥글지 않게요.']),

('마운틴 클라이머', '코어', array['유산소','복합'], array['체중 감량','체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['코어','허벅지 앞','어깨'], array['손목'], array['매트'],
 false, 4, 3, 20, 12, 30, null, null, null,
 '높은 플랭크 자세에서 무릎을 가슴 쪽으로 번갈아 당겨요.',
 '엉덩이가 솟지 않게.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 무릎을 가슴까지 끌어와요.','{count}, 엉덩이가 솟지 않게요.','{count}, 빠르게 교차해요.']),

('데드 버그', '코어', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['warmup','main'],
 array['코어'], array[]::text[], array['매트'],
 false, 2, 3, 12, 8, 18, null, null, null,
 '누워 팔다리를 천장으로 든 뒤 반대편을 동시에 펴 내렸다 돌아와요.',
 '허리가 바닥에서 뜨지 않게.',
 e_easy, m_general, f_gentle, array[]::text[], '',
 array['{count}, 반대편 팔다리 동시에 내려요.','{count}, 허리가 뜨지 않게요.','{count}, 천천히 돌아와요.']),

('버드 도그', '코어', array['근력'], array['자세 개선'],
 array['집','야외','헬스장'], array['warmup','main'],
 array['코어','등','엉덩이'], array[]::text[], array['매트'],
 false, 2, 3, 12, 8, 18, null, null, null,
 '네발 자세에서 반대편 팔다리를 동시에 뻗었다 돌아와요.',
 '허리 일직선 유지에 집중.',
 e_easy, m_general, f_gentle, array[]::text[], '',
 array['{count}, 반대편 팔다리 동시에 뻗어요.','{count}, 허리 일직선 유지.','{count}, 골반이 기울지 않게요.']),

('V-up', '코어', array['근력'], array['체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['상복부','하복부'], array['허리','목'], array['매트'],
 false, 4, 3, 10, 6, 14, null, null, null,
 '누운 자세에서 다리와 상체를 동시에 들어 손이 발끝에 닿게요.',
 '허리에 무리. 초보자는 패스.',
 e_focus, m_general, f_strong, array[]::text[], '',
 array['{count}, 다리와 상체 동시에 들어요.','{count}, 손이 발끝에 닿도록요.','{count}, 천천히 내려요.']),

('호로우 락', '코어', array['근력'], array['체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['코어'], array['허리','목'], array['매트'],
 false, 4, 3, 12, 6, 18, null, null, null,
 '할로우 홀드 자세에서 몸을 앞뒤로 살짝 흔들어요.',
 '허리 통증 시 즉시 중단.',
 e_focus, m_general, f_strong, array[]::text[], '',
 array['{count}, 할로우 자세로 앞뒤 흔들어요.','{count}, 복근에 힘 단단히.','{count}, 허리는 바닥 눌러요.']),

('토 터치', '코어', array['근력','유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['main'],
 array['상복부','햄스트링'], array['허리'], array['매트'],
 false, 2, 3, 12, 8, 18, null, null, null,
 '누워 다리를 천장으로 들고 손으로 발끝을 짚으러 상체를 말아요.',
 '햄스트링이 뻣뻣하면 무릎 살짝 굽혀요.',
 e_easy, m_general, f_gentle, array[]::text[], '',
 array['{count}, 다리 천장으로 들어요.','{count}, 손으로 발끝 짚으러요.','{count}, 상체만 말아 올려요.']),

('덤벨 사이드 벤드', '코어', array['근력'], array['자세 개선'],
 array['집','헬스장'], array['main'],
 array['옆구리'], array['허리'], array['덤벨'],
 false, 3, 3, 12, 8, 18, null, null, null,
 '한 손에 덤벨을 들고 그쪽으로 옆구리를 굽혔다 똑바로 돌아와요.',
 '반대편 옆구리에 힘 주며 일어나요.',
 e_general, m_dumbbell, f_general, array[]::text[], '',
 array['{count}, 덤벨 든 쪽으로 옆구리 굽혀요.','{count}, 천천히 똑바로 돌아와요.','{count}, 반대쪽 옆구리 자극 느껴요.']),

-- ============================================================
-- 전신 (61-80) : 복합 동작·유산소·기능성
-- ============================================================
('버피', '전신', array['복합','유산소'], array['체중 감량','체력 향상'],
 array['야외','헬스장'], array['main'],
 array['전신'], array['무릎','허리','손목'], array[]::text[],
 true, 5, 3, 10, 5, 14, null, null, null,
 '서서 → 스쿼트 → 푸시업 자세 → 점프 한 사이클을 반복해요.',
 '강도 매우 높음. 무릎/허리 안 좋으면 점프 빼고 스텝으로.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 스쿼트 푸시업 점프 한 사이클.','{count}, 점프 부드럽게 착지.','{count}, 호흡 끊지 마세요.']),

('점핑잭', '전신', array['유산소'], array['체중 감량','체력 향상'],
 array['야외','헬스장'], array['warmup','main'],
 array['전신','종아리'], array['무릎'], array[]::text[],
 true, 3, 3, 25, 15, 40, null, null, null,
 '제자리에서 점프하며 팔과 다리를 동시에 벌렸다 모아요.',
 '무릎 부담 시 발만 옆으로 빼는 스텝잭으로.',
 e_easy, m_cardio, f_general, array[]::text[], '',
 array['{count}, 팔다리 동시에 벌려요.','{count}, 발은 가볍게 착지요.','{count}, 리듬 유지하세요.']),

('하이 니', '전신', array['유산소'], array['체중 감량','체력 향상'],
 array['야외','헬스장'], array['main'],
 array['전신','코어'], array['무릎'], array[]::text[],
 true, 4, 3, 20, 12, 30, null, null, null,
 '제자리에서 무릎을 허리 높이까지 올리며 빠르게 뛰어요.',
 '무릎 부담 시 천천히 또는 스텝으로.',
 e_general, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 무릎을 허리 높이까지요.','{count}, 빠르게 교차해요.','{count}, 코어로 들어 올려요.']),

('스피드 스케이터', '전신', array['유산소','복합'], array['체중 감량','체력 향상'],
 array['야외','헬스장'], array['main'],
 array['엉덩이','허벅지','코어'], array['무릎'], array[]::text[],
 true, 4, 3, 16, 10, 24, null, null, null,
 '좌우로 크게 옆 점프하며 스케이트 타듯 반대 발을 뒤로 보내요.',
 '무릎 부담 시 점프 없이 사이드 스텝으로.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 옆으로 크게 점프요.','{count}, 반대 발을 뒤로 보내요.','{count}, 스케이트 타듯 가요.']),

('토끼뜀', '전신', array['유산소','복합'], array['체중 감량','체력 향상'],
 array['야외','헬스장'], array['main'],
 array['하체','전신'], array['무릎','허리'], array[]::text[],
 true, 4, 3, 10, 6, 14, null, null, null,
 '쪼그려 앉은 자세에서 앞으로 폭발적으로 점프해요.',
 '무릎 부담 큼. 통증 시 중단.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 쪼그려 앉아 폭발적 점프.','{count}, 부드럽게 착지하세요.','{count}, 무릎 부담 크면 멈춰요.']),

('사이드 셔플', '전신', array['유산소'], array['체력 향상'],
 array['집','야외','헬스장'], array['warmup','main'],
 array['하체','코어'], array[]::text[], array[]::text[],
 false, 3, 3, 20, 12, 30, null, null, null,
 '발을 어깨 너비로 좌우로 빠르게 스텝해요. 점프 없음.',
 '',
 e_easy, m_cardio, f_general, array[]::text[], '',
 array['{count}, 어깨 너비로 좌우 스텝요.','{count}, 코어 단단히 잡아요.','{count}, 빠르게 리듬 타요.']),

('박스 점프', '전신', array['복합','유산소'], array['체력 향상'],
 array['헬스장'], array['main'],
 array['하체','전신'], array['무릎','허리'], array[]::text[],
 true, 5, 3, 8, 4, 12, null, null, null,
 '안정된 박스나 단차에 양발로 점프해 올라섰다 내려와요.',
 '발목/무릎 약하면 금지. 박스 안정성 필수.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 박스에 양발 점프 올라가요.','{count}, 무릎으로 흡수하며 착지요.','{count}, 박스 안정성 확인했어요?']),

('점프 로프', '전신', array['유산소'], array['체중 감량','체력 향상'],
 array['야외','헬스장'], array['main'],
 array['종아리','전신'], array['무릎'], array[]::text[],
 true, 4, null, null, null, null, 60, 30, 180,
 '줄넘기를 일정 리듬으로 뛰어요. 실제 줄 없이 동작만도 가능.',
 '무릎 부담 시 짧게 끊어서.',
 array[]::text[], array[]::text[], array[]::text[],
 array['발 앞꿈치로 가볍게 뛰어요.','어깨는 가만히, 손목으로 돌려요.','리듬 유지하세요.','호흡 같이 가요.','시선은 앞을 봐요.'],
 '절반 지났어요. 리듬 유지해요.',
 array[]::text[]),

('베어 크롤', '전신', array['복합','근력'], array['체중 감량','체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['전신','코어','어깨'], array['손목'], array[]::text[],
 false, 3, 3, 12, 8, 18, null, null, null,
 '네발 자세에서 무릎을 살짝 띄우고 곰처럼 손발 교차로 기어가요.',
 '엉덩이가 너무 솟지 않게.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 무릎 살짝 띄우고 교차로 기어요.','{count}, 엉덩이가 솟지 않게요.','{count}, 코어 단단히.']),

('크랩 워크', '전신', array['복합','근력'], array['체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['삼두','엉덩이','코어'], array['손목','어깨'], array[]::text[],
 false, 3, 3, 12, 8, 18, null, null, null,
 '엉덩이를 든 채 손발로 지지하며 게처럼 옆으로 걸어요.',
 '손목 부담 큰 동작.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 엉덩이 든 채 옆으로 걸어요.','{count}, 손목 부담되면 천천히요.','{count}, 엉덩이 안 떨어지게요.']),

('인치웜', '전신', array['복합','유연성'], array['체력 향상'],
 array['집','야외','헬스장'], array['warmup','main'],
 array['어깨','코어','햄스트링'], array[]::text[], array[]::text[],
 false, 2, 3, 10, 5, 15, null, null, null,
 '선 자세에서 손으로 바닥을 짚고 푸시업 자세까지 걸어갔다 돌아와요.',
 '햄스트링이 뻣뻣하면 무릎 살짝 굽혀요.',
 e_easy, m_cardio, f_gentle, array[]::text[], '',
 array['{count}, 손으로 바닥 천천히 걸어 나가요.','{count}, 플랭크까지 도달해요.','{count}, 돌아와서 일어나요.']),

('클라이밍 트위스트', '전신', array['복합','유산소'], array['체중 감량'],
 array['집','야외','헬스장'], array['main'],
 array['코어','옆구리','어깨'], array['손목','허리'], array['매트'],
 false, 4, 3, 14, 8, 20, null, null, null,
 '플랭크 자세에서 무릎을 반대편 팔꿈치 쪽으로 비스듬히 가져와요.',
 '엉덩이가 솟지 않게.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 무릎을 반대편 팔꿈치로요.','{count}, 엉덩이가 솟지 않게요.','{count}, 빠르게 교차요.']),

('스쿼트 푸시업 콤보', '전신', array['복합'], array['체중 감량','체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['전신'], array['무릎','손목'], array[]::text[],
 false, 5, 3, 8, 5, 12, null, null, null,
 '스쿼트 1회 → 손 짚고 푸시업 자세로 가서 푸시업 1회 → 돌아오기.',
 '강도 매우 높음.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 스쿼트 1회로 시작해요.','{count}, 손 짚고 푸시업 자세로요.','{count}, 푸시업 후 돌아오기.']),

('점프 푸시업', '전신', array['복합','유산소'], array['체력 향상'],
 array['야외','헬스장'], array['main'],
 array['전신','가슴'], array['손목','어깨','허리'], array[]::text[],
 true, 5, 3, 8, 4, 10, null, null, null,
 '푸시업 내려갔다 폭발적으로 밀어 손을 띄워요.',
 '손목·어깨 부담 매우 큼.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 푸시업 내려갔다 폭발적으로요.','{count}, 손을 살짝 띄우세요.','{count}, 부드럽게 착지해요.']),

('인치웜 푸시업', '전신', array['복합'], array['체중 감량','체력 향상'],
 array['집','야외','헬스장'], array['main'],
 array['전신','가슴','코어'], array['손목'], array[]::text[],
 false, 4, 3, 8, 5, 12, null, null, null,
 '인치웜으로 푸시업 자세까지 간 뒤 푸시업 한 번, 돌아오기 반복.',
 '난이도 높음. 푸시업 빼고 인치웜만도 OK.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 인치웜으로 푸시업 자세까지.','{count}, 푸시업 한 번 추가요.','{count}, 돌아와서 일어나요.']),

('덤벨 스러스터', '전신', array['복합'], array['체중 감량','체력 향상'],
 array['집','헬스장'], array['main'],
 array['하체','어깨','코어'], array['무릎','어깨'], array['덤벨'],
 false, 4, 3, 10, 6, 14, null, null, null,
 '덤벨을 어깨에 들고 스쿼트 → 일어나며 머리 위로 밀어요.',
 '코어 단단히 잡아야 허리 보호.',
 e_focus, m_dumbbell, f_strong, array[]::text[], '',
 array['{count}, 덤벨 어깨에 들고 스쿼트.','{count}, 일어나며 머리 위로 밀어요.','{count}, 코어 단단히 잡아요.']),

('덤벨 클린', '전신', array['복합','근력'], array['체력 향상'],
 array['헬스장'], array['main'],
 array['전신'], array['허리','어깨','무릎'], array['덤벨'],
 false, 5, 3, 8, 4, 10, null, null, null,
 '바닥에서 덤벨을 폭발적으로 들어 어깨까지 올려요.',
 '기술 동작. 폼 익힌 뒤 무게 늘려요.',
 e_focus, m_dumbbell, f_strong, array[]::text[], '',
 array['{count}, 바닥에서 폭발적으로 들어요.','{count}, 어깨까지 한 번에 올려요.','{count}, 천천히 내려놓아요.']),

('덤벨 스윙', '전신', array['복합','유산소'], array['체중 감량','체력 향상'],
 array['집','헬스장'], array['main'],
 array['엉덩이','허벅지 뒤','코어'], array['허리'], array['덤벨'],
 false, 4, 3, 12, 8, 18, null, null, null,
 '덤벨 하나를 양손으로 들고 엉덩이 힘으로 어깨 높이까지 흔들어 올려요.',
 '팔 힘 쓰지 말고 엉덩이 추진력으로.',
 e_focus, m_cardio, f_strong, array[]::text[], '',
 array['{count}, 엉덩이 추진력으로 흔들어요.','{count}, 어깨 높이까지 올려요.','{count}, 팔 힘 쓰지 마세요.']),

('덤벨 터키시 겟업', '전신', array['복합','근력'], array['체력 향상','자세 개선'],
 array['집','헬스장'], array['main'],
 array['전신','코어'], array['어깨','허리'], array['덤벨','매트'],
 false, 3, 3, 6, 3, 10, null, null, null,
 '누운 자세에서 한 손에 덤벨을 천장으로 들고 천천히 일어났다 다시 누워요.',
 '기술 동작. 가벼운 무게로 시작.',
 e_focus, m_dumbbell, f_general, array[]::text[], '',
 array['{count}, 누운 자세에서 천천히 일어나요.','{count}, 덤벨은 항상 천장 향하게요.','{count}, 동작 하나하나 정확히.']),

('덤벨 윈드밀', '전신', array['복합','유연성'], array['자세 개선'],
 array['집','헬스장'], array['main'],
 array['코어','옆구리','어깨'], array['허리','어깨'], array['덤벨'],
 false, 3, 3, 10, 6, 14, null, null, null,
 '덤벨을 천장으로 든 채 반대편으로 상체를 숙여 발끝을 향해요.',
 '시선은 항상 덤벨에 고정.',
 e_focus, m_dumbbell, f_general, array[]::text[], '',
 array['{count}, 덤벨을 천장 향해 들어요.','{count}, 옆으로 천천히 숙여요.','{count}, 시선은 덤벨에 고정.']),

-- ============================================================
-- 스트레칭 (81-100) : 워밍업·마무리·회복
-- ============================================================
-- 워밍업 (81-87) : 동적 스트레칭, 관절 활성화
('어깨 회전', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['warmup'],
 array['어깨'], array[]::text[], array[]::text[],
 false, 1, null, null, null, null, 45, 20, 90,
 '팔을 옆으로 크게 원을 그리며 앞·뒤로 회전해요.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['팔을 옆으로 펼치세요.','앞으로 천천히 원을 그려요.','점점 크게 그려보세요.','반대로 뒤로 돌려요.','어깨 힘 빼고 부드럽게요.'],
 '절반 지났어요. 호흡 유지하세요.',
 array[]::text[]),

('골반 회전', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['warmup'],
 array['고관절','코어'], array[]::text[], array[]::text[],
 false, 1, null, null, null, null, 30, 15, 60,
 '서서 손을 허리에 얹고 골반으로 크게 원을 그리듯 돌려요.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['손을 허리에 얹어요.','골반으로 천천히 원을 그려요.','점점 크게요.','반대 방향으로 돌려요.','호흡 유지하세요.'],
 '절반 지났어요. 부드럽게요.',
 array[]::text[]),

('발목 회전', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['warmup'],
 array['발목'], array[]::text[], array[]::text[],
 false, 1, null, null, null, null, 30, 15, 60,
 '한 발을 들어 발목을 원을 그리며 좌우 양방향으로 천천히 돌려요.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['한 발을 들어 발끝을 띄워요.','발목으로 원을 천천히 그려요.','반대 방향도 돌려요.','반대 발도 해요.'],
 '반대쪽도 곧 해요.',
 array[]::text[]),

('목 회전', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['warmup'],
 array['목'], array[]::text[], array[]::text[],
 false, 1, null, null, null, null, 30, 15, 60,
 '고개를 좌·우·앞·뒤로 천천히 굴리며 목 주변을 풀어요.',
 '빠르게 돌리지 마세요.',
 array[]::text[], array[]::text[], array[]::text[],
 array['고개를 천천히 좌우로 굴려요.','앞뒤로 천천히 움직여요.','원을 그리듯 부드럽게요.','빠르게 돌리지 마세요.'],
 '천천히 호흡하세요.',
 array[]::text[]),

('캣카우', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['warmup','cooldown'],
 array['척추','코어'], array[]::text[], array['매트'],
 false, 1, null, null, null, null, 45, 20, 90,
 '네발 자세에서 등을 둥글게 말았다 아래로 늘어뜨리며 호흡과 함께 움직여요.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['네발 자세 잡아요.','숨 들이마시며 등을 아래로요.','내쉬며 등을 둥글게 말아요.','턱은 가슴 쪽으로요.','호흡 리듬에 맞춰 천천히요.'],
 '절반 지났어요. 호흡 깊게요.',
 array[]::text[]),

('다이내믹 햄스트링 스윙', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['warmup'],
 array['햄스트링','고관절'], array['허리'], array[]::text[],
 false, 2, null, null, null, null, 45, 20, 90,
 '한 다리를 앞뒤로 크게 흔들어 햄스트링과 고관절을 동적으로 풀어요.',
 '균형 어려우면 벽을 짚어요.',
 array[]::text[], array[]::text[], array[]::text[],
 array['한 다리를 앞뒤로 흔들어요.','점점 크게 스윙요.','균형 잡으며 천천히요.','반대 다리도 해요.'],
 '반대쪽도 곧 해요.',
 array[]::text[]),

('측면 스트레칭', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['warmup','cooldown'],
 array['옆구리','등'], array[]::text[], array[]::text[],
 false, 1, null, null, null, null, 30, 15, 60,
 '서서 한 팔을 머리 위로 뻗어 반대편으로 상체를 기울여요.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['한 팔을 머리 위로 뻗어요.','반대편으로 상체 기울여요.','옆구리 늘어나는 느낌요.','반대쪽도 곧 해요.'],
 '반대쪽도 곧 해요.',
 array[]::text[]),

-- 마무리 (88-94) : 정적 스트레칭
('햄스트링 스트레칭', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['cooldown'],
 array['햄스트링'], array['허리'], array['매트'],
 false, 1, null, null, null, null, 30, 15, 60,
 '한 다리를 앞으로 뻗어 발끝을 잡듯 상체를 천천히 숙여요.',
 '반동 쓰지 말고 호흡으로.',
 array[]::text[], array[]::text[], array[]::text[],
 array['한 다리 앞으로 펴요.','발끝을 잡듯 상체 숙여요.','호흡으로 더 깊게요.','반동 쓰지 마세요.'],
 '반대쪽도 곧 해요.',
 array[]::text[]),

('쿼드 스트레칭', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['cooldown'],
 array['허벅지 앞'], array['무릎'], array[]::text[],
 false, 1, null, null, null, null, 30, 15, 60,
 '서서 한 발을 뒤로 들어 발등을 손으로 잡고 엉덩이 쪽으로 당겨요.',
 '균형 어려우면 벽 짚어요.',
 array[]::text[], array[]::text[], array[]::text[],
 array['한 발을 뒤로 들어요.','발등을 손으로 잡아요.','엉덩이 쪽으로 당겨요.','균형 어려우면 벽 짚어요.'],
 '반대쪽도 곧 해요.',
 array[]::text[]),

('종아리 스트레칭', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['cooldown'],
 array['종아리'], array[]::text[], array[]::text[],
 false, 1, null, null, null, null, 30, 15, 60,
 '벽을 짚고 한 발을 뒤로 보내 뒤꿈치를 바닥에 누른 채 종아리를 늘려요.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['벽을 짚고 한 발 뒤로요.','뒤꿈치를 바닥에 누르세요.','종아리 늘어나는 느낌요.','반대쪽도 해요.'],
 '반대쪽도 곧 해요.',
 array[]::text[]),

('차일드 포즈', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['cooldown'],
 array['허리','등','어깨'], array[]::text[], array['매트'],
 false, 1, null, null, null, null, 45, 20, 90,
 '무릎 꿇고 엉덩이를 발뒤꿈치로 내린 뒤 팔을 앞으로 뻗어 이마를 바닥에.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['무릎 꿇고 엉덩이 발뒤꿈치로요.','팔을 앞으로 뻗어요.','이마는 바닥에요.','어깨 힘 빼고 호흡하세요.'],
 '절반 지났어요. 어깨 힘 빼세요.',
 array[]::text[]),

('비둘기 자세', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['cooldown'],
 array['엉덩이','고관절'], array['무릎'], array['매트'],
 false, 2, null, null, null, null, 45, 20, 90,
 '한 다리를 앞으로 굽혀 정강이를 매트 옆으로, 뒷다리는 곧게 펴고 상체를 숙여요.',
 '무릎 통증 시 부드럽게.',
 array[]::text[], array[]::text[], array[]::text[],
 array['한 다리 앞으로 굽혀요.','정강이를 매트 옆으로요.','뒷다리는 곧게 펴요.','상체를 천천히 숙여요.'],
 '반대쪽도 곧 해요.',
 array[]::text[]),

('나비 자세', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['cooldown'],
 array['고관절','허벅지 안쪽'], array[]::text[], array['매트'],
 false, 1, null, null, null, null, 45, 20, 90,
 '앉아 발바닥을 마주 댄 뒤 무릎을 좌우로 부드럽게 내려요.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['앉아 발바닥을 마주 대요.','무릎을 좌우로 부드럽게.','상체를 살짝 앞으로요.','호흡으로 더 깊게요.'],
 '절반 지났어요. 호흡 깊게요.',
 array[]::text[]),

('누운 척추 트위스트', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['cooldown'],
 array['척추','옆구리'], array['허리'], array['매트'],
 false, 1, null, null, null, null, 45, 20, 90,
 '누운 자세에서 무릎을 한쪽으로 넘기고 상체는 반대쪽을 향해요.',
 '허리 통증 시 천천히.',
 array[]::text[], array[]::text[], array[]::text[],
 array['누워서 무릎을 한쪽으로요.','상체는 반대쪽 향해요.','시선은 손끝 따라가요.','호흡 유지하세요.'],
 '반대쪽도 곧 해요.',
 array[]::text[]),

-- 회복 (95-100) : 호흡·이완·정적 휴식
('박스 호흡', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['recovery'],
 array['횡격막'], array[]::text[], array[]::text[],
 false, 1, null, null, null, null, 90, 60, 180,
 '4초 들이마시고, 4초 멈추고, 4초 내쉬고, 4초 멈추는 박스 호흡을 반복해요.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['4초간 코로 들이마셔요.','4초간 숨을 멈춰요.','4초간 입으로 내쉬어요.','4초간 다시 멈춰요.','이 사이클을 반복하세요.'],
 '절반 지났어요. 박스를 그리듯 호흡요.',
 array[]::text[]),

('디아프램 호흡', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['recovery'],
 array['횡격막','코어'], array[]::text[], array['매트'],
 false, 1, null, null, null, null, 90, 60, 180,
 '누워 배에 손을 얹고 코로 깊이 들이마셔 배를 부풀렸다 천천히 내쉬어요.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['배에 손을 얹어요.','코로 깊게 들이마셔요. 배가 부풀어요.','입으로 천천히 내쉬어요.','어깨는 움직이지 않게요.','호흡에만 집중해요.'],
 '절반 지났어요. 호흡 천천히요.',
 array[]::text[]),

('다리 벽에 올리기', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','헬스장'], array['recovery'],
 array['하체','등'], array[]::text[], array['매트'],
 false, 1, null, null, null, null, 120, 60, 300,
 '엉덩이를 벽에 가까이 두고 누워 다리를 벽에 곧게 올린 채 휴식해요.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['엉덩이 벽에 가까이 두고 누워요.','다리를 벽에 곧게 올려요.','팔은 옆으로 편안하게요.','깊게 호흡하세요.','온몸의 긴장 풀어요.'],
 '절반 지났어요. 마음 가라앉히세요.',
 array[]::text[]),

('사바아사나', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['recovery'],
 array['전신'], array[]::text[], array['매트'],
 false, 1, null, null, null, null, 180, 60, 300,
 '편안하게 누워 눈을 감고 발끝부터 머리까지 차례로 힘을 빼며 휴식해요.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['편안하게 누우세요.','눈을 감아요.','발끝부터 머리까지 힘 빼요.','호흡에만 집중하세요.','마음을 가라앉혀요.'],
 '절반 지났어요. 그대로 편안하게요.',
 array[]::text[]),

('무릎 가슴 안기', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['cooldown','recovery'],
 array['허리','엉덩이'], array[]::text[], array['매트'],
 false, 1, null, null, null, null, 45, 20, 90,
 '누워서 양 무릎을 가슴 쪽으로 끌어안고 허리를 늘려요.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['누워서 양 무릎 가슴으로 안아요.','깊게 호흡하세요.','허리가 늘어나는 느낌요.','어깨 힘 빼고요.'],
 '절반 지났어요. 호흡 깊게요.',
 array[]::text[]),

('점진적 근육 이완', '스트레칭', array['유연성'], array['자세 개선'],
 array['집','야외','헬스장'], array['recovery'],
 array['전신'], array[]::text[], array['매트'],
 false, 1, null, null, null, null, 180, 90, 300,
 '발끝부터 시작해 차례로 근육에 힘을 줬다 빼며 전신의 긴장을 풀어요.',
 '',
 array[]::text[], array[]::text[], array[]::text[],
 array['발끝부터 시작해요. 힘 줬다 빼요.','종아리, 허벅지 차례로요.','복부, 가슴, 어깨까지요.','팔과 손, 얼굴까지요.','온몸이 풀렸어요. 호흡 유지요.'],
 '절반 지났어요. 천천히 호흡요.',
 array[]::text[]);

end $$;

-- ============================================================
-- 시드 결과 분포 검증 (참고용 — 실행 후 직접 확인)
-- ============================================================
-- select body_region, count(*) from public.exercises group by body_region order by 1;
-- → 상체:20  하체:20  코어:20  전신:20  스트레칭:20
--
-- select unnest(phase_tags) phase, count(*)
--   from public.exercises group by phase order by 2 desc;
-- → main 70+, cooldown 10+, warmup 14+, recovery 6
--
-- select unnest(goal_tags) goal, count(*)
--   from public.exercises group by goal order by 2 desc;
--
-- select count(*) from public.exercises where array_length(form_cues, 1) > 0;
-- → 74 (세트 기반만 form_cues 채워짐)
--
-- select count(*) from public.exercises where array_length(time_scripts, 1) > 0;
-- → 26 (시간 기반만 time_scripts 채워짐)
